In [2]:
import numpy as np
import os
import time
from keras import backend as K
from keras import applications
from keras.preprocessing.image import ImageDataGenerator
from keras import optimizers
from keras.models import Sequential, Model, load_model 
from keras.layers import Dropout, Flatten, Dense, GlobalAveragePooling2D, Input
from keras import backend as k 
from keras.callbacks import ModelCheckpoint, LearningRateScheduler, TensorBoard, EarlyStopping
from keras.optimizers import Adam, RMSprop, SGD
from keras.preprocessing.image import ImageDataGenerator

from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

Using TensorFlow backend.


In [3]:
import cv2
import pickle
%matplotlib inline
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

In [4]:
def data_to_features(model,path,out):
    feature_dict={0:[],1:[]}
    classes=['0','1']
    for i in classes:
        l=os.listdir(path+i+'/')
        for j in l:
            im = cv2.imread(path+i+'/'+j)
            im = cv2.resize(cv2.cvtColor(im, cv2.COLOR_BGR2RGB), (224, 224)).astype(np.float32) / 255.0
            im = np.expand_dims(im, axis =0)
            feature_dict[int(i)].append(model.predict(im))
    pickle.dump(feature_dict, open(out, "wb" ))
    return feature_dict

In [5]:
model=load_model('tune_model.h5')
model_till_flatten = Model(input=model.input,output=model.get_layer('flatten').output)
model_till_fc1 = Model(input=model.input,output=model.get_layer('fc1').output)

Instructions for updating:
keep_dims is deprecated, use keepdims instead
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Instructions for updating:
keep_dims is deprecated, use keepdims instead


In [10]:
feature_dict0=data_to_features(model_till_flatten,'data/train/','features_till_flatten.pkl')

In [18]:
feature_dict1=data_to_features(model_till_fc1,'data/train/','features_till_fc1.pkl')

In [16]:
feature_dict0[0][0].shape

(1, 25088)

In [19]:
feature_dict1[0][0].shape

(1, 4096)

In [20]:
feature_dict0

{0: [array([[0.0000000e+00, 5.3789174e+22, 0.0000000e+00, ..., 0.0000000e+00,
          7.4159007e+21, 0.0000000e+00]], dtype=float32),
  array([[0.0000000e+00, 4.9617306e+22, 0.0000000e+00, ..., 0.0000000e+00,
          6.7098512e+21, 0.0000000e+00]], dtype=float32),
  array([[0.0000000e+00, 5.3623334e+22, 0.0000000e+00, ..., 0.0000000e+00,
          7.1442661e+21, 0.0000000e+00]], dtype=float32),
  array([[0.0000000e+00, 5.3523759e+22, 0.0000000e+00, ..., 0.0000000e+00,
          7.3607035e+21, 0.0000000e+00]], dtype=float32),
  array([[0.0000000e+00, 5.1942667e+22, 0.0000000e+00, ..., 0.0000000e+00,
          7.1939757e+21, 0.0000000e+00]], dtype=float32),
  array([[0.000000e+00, 5.320255e+22, 0.000000e+00, ..., 0.000000e+00,
          7.330445e+21, 0.000000e+00]], dtype=float32),
  array([[0.0000000e+00, 5.4657842e+22, 0.0000000e+00, ..., 0.0000000e+00,
          7.5034732e+21, 0.0000000e+00]], dtype=float32),
  array([[0.000000e+00, 5.380960e+22, 0.000000e+00, ..., 0.000000e+00,
 

In [6]:
feature_dict2=data_to_features(model_till_flatten,'data/validation/','features_till_flatten_validation.pkl')